### ISSUE TITLE
License

### ISSUE THREAD

**Issue by TeamColaDev** [maisans-maid/Mai#129]
I plan on rescripting this entire bot, will I need to give credit to you after I've rescripted the entire bot?

**Comment by kakarot-dev** [comment]
most probably u are not allowed to do that
still if u plan on doing that id recommend joining the support server first and have a talk with mai and conqr

**Comment by BearTS** [comment]
@teamcoladev yes you will need to give credit to us since the source code is licensed under MIT license which makes it compulsory to give credit.

**Comment by kakarot-dev** [comment]
@TeamColaDev i encountered a bot named mai ( beta ) in discord.bots.gg I am assuming that was your bot cuz it the owner was named something close to colaa. 

We would appreciate it, if you remove the bot from the dbots queue to be approved

The reason being : No credits were given and the bot is a full copy of the mai v4 instead of being rescripted version.
