### ISSUE TITLE
Notice of Possible DMCA Takedown

### ISSUE THREAD

**Issue by conqr2** [maisans-maid/Mai#20]
Hi there,

On your not finished but proposed website ([https://maisans-maid.github.io/mai.moe/](https://maisans-maid.github.io/mai.moe/)) it seems to be a Colorlib template, with all the backlinks forcefully removed / hidden. This is a direct violation of the Colorlib license and terms and may result in a DMCA takedown issued to you from them.

**Comment by maisans-maid** [comment]
It is indeed from colorlib template, but im not developing the site any more further. I stopped finishing it when I moved to another site. I haven't received any takedown issue from them but nonetheless this is still convenient. In fact I was just idly waiting for it to happen. Thank you for notifying though. I expected it from the beginning, since the site was never made to promote something, it just happens that the bot was a good content to train with.
